### ISSUE TITLE
Random issue

### ISSUE THREAD

**Issue by s5msft** [s5msft/WinObjC#4]
- [ ] Do the first thing #1 
- [ ] Do the second #2 
- [ ] Do the third #3 
- [ ] Do the fourth
